// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptv8DnhqxGYjjKSzrriGdvQ8mHSo_hVs',
    appId: '1:435889449146:web:2774f2a94c95432303fa83',
    messagingSenderId: '435889449146',
    projectId: 'balancetracker-4862d',
    authDomain: 'balancetracker-4862d.firebaseapp.com',
    storageBucket: 'balancetracker-4862d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXdBuIdvX7SYUp2EClRDgA2soT3BBl3U',
    appId: '1:435889449146:android:abc72ff0624e148403fa83',
    messagingSenderId: '435889449146',
    projectId: 'balancetracker-4862d',
    storageBucket: 'balancetracker-4862d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtpJ-CURoYPAPu1aNqnnnWnOfJQR04rI',
    appId: '1:435889449146:ios:7988ef64e0cba8c503fa83',
    messagingSenderId: '435889449146',
    projectId: 'balancetracker-4862d',
    storageBucket: 'balancetracker-4862d.firebasestorage.app',
    iosBundleId: 'com.example.balanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtpJ-CURoYPAPu1aNqnnnWnOfJQR04rI',
    appId: '1:435889449146:ios:7988ef64e0cba8c503fa83',
    messagingSenderId: '435889449146',
    projectId: 'balancetracker-4862d',
    storageBucket: 'balancetracker-4862d.firebasestorage.app',
    iosBundleId: 'com.example.balanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptv8DnhqxGYjjKSzrriGdvQ8mHSo_hVs',
    appId: '1:435889449146:web:97b18daef33fb9bd03fa83',
    messagingSenderId: '435889449146',
    projectId: 'balancetracker-4862d',
    authDomain: 'balancetracker-4862d.firebaseapp.com',
    storageBucket: 'balancetracker-4862d.firebasestorage.app',
  );
}
